### ISSUE TITLE
Unable to select subfolder under Download for downloads

### ISSUE THREAD

**Issue by superbonaci** [a-pavlov/jed2k#35]
I'm trying to set for downloads the directory `/storage/emulated/0/Download/ed2k/`. However it's unable to select that folder, just defaults it to `/storage/emulated/0/`. Choosing `/storage/emulated/0/ed2k/` instead does work.
The `Download` folder already exists on android devices on internal storage.

**Comment by superbonaci** [comment]
Here's the logcat:

````
06-28 10:48:06.329  5850 18838 D MARsPolicyManager: onPackageResumedFG pkgName = org.dkf.jmule, userId = 0
06-28 10:48:06.338  5850 20293 V WindowManager: Relayout Window{8b4c178 u0 org.dkf.jmule/org.dkf.jmule.activities.SettingsActivity}: viewVisibility=4 req=1080x2280
06-28 10:48:06.346  5850  5973 D CodecSolution: isMaxAspectPackageEx: org.dkf.jmule : false(0)
06-28 10:48:06.348  3466  3490 D OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x781c234c00
06-28 10:48:06.349  5850 19928 D WindowManager: focusedDisplayId : 0
06-28 10:48:06.349  5850 19928 D WindowManager: display doesn't have focus
06-28 10:48:06.352  5850  5973 I PerfSDKService: Current foregroundpackage name : org.dkf.jmule
06-28 10:48:06.353  5850 18566 D PkgPredictorService: org.dkf.jmule go to foreground!
06-28 10:48:06.353  5390 26779 W IAudioFlinger: onTransact: transaction 9 received from PID 21050 unauthorized UID 10304
06-28 10:48:06.354 18712 18921 D OpenGLRenderer: makeCurrent EglSurface : 0x779ab06d00 -> 0x7820c69380
06-28 10:48:06.354  5850 19106 D AS.AudioService: Master mute false, 0, user=0
06-28 10:48:06.355  5850 18566 D PkgPredictorService: previous pkgs: org.dkf.jmule running pkg: org.dkf.jmule, uid: 0 is system: false
06-28 10:48:06.355  5390 26779 W IAudioFlinger: onTransact: transaction 9 received from PID 21050 unauthorized UID 10304
06-28 10:48:06.355  5850 18566 D PkgPredictorService-Collector: save record...
06-28 10:48:06.355  5850 18566 D PkgPredictorService-Collector:  (hour:10 day:1 previous:[org.dkf.jmule] activityName:unknown running:org.dkf.jmule userId:0 screenOrientation:0 wifi:0 bt:0 predictTime:1 apkVersion:2.3 consumeTime:-1 preloaded:false>)
06-28 10:48:06.355  5850 18566 D PkgPredictorService-NapPreloadController: User using: org.dkf.jmule
06-28 10:48:06.363  5850  5975 D GamePkgDataHelper: getSosPolicy(). org.dkf.jmule
06-28 10:48:06.364  5850  5975 D GameManagerService: identifyGamePackage. org.dkf.jmule, mCurrentUserId: 0, callerUserId: 0
06-28 10:48:06.364  5850  5975 D GamePkgDataHelper: getGamePkgData(). org.dkf.jmule
06-28 10:48:06.364  5850  5975 D GameManagerService: noteResumeComponent(), resumeComponent: org.dkf.jmule
06-28 10:48:06.364  5850 18657 D GameManagerService: handleForegroundChange(). pkgName: org.dkf.jmule, clsName: org.dkf.jmule.activities.SettingsActivity,FgActivityName:org.dkf.jmule/.activities.SettingsActivity,userID:0
06-28 10:48:06.364  5850 18657 D GameManagerService:   handleForegroundChange(). set mFgApp: org.dkf.jmule
06-28 10:48:06.364  5850 18657 D GameManagerService: notifyResumePause(). pkg: org.dkf.jmule, type: 4, isMinimized: false, isTunableApp: false
06-28 10:48:06.364  5850 18657 D GameManagerService:   notifyResumePause(). do nothing. mKillNotiCount: 1
06-28 10:48:06.368  5850 19106 D GamePkgDataHelper: getSosPolicy(). org.dkf.jmule
06-28 10:48:06.371  5850  5850 D ConnectivityService: filterNetworkStateForUid() uid: 10028, pid: 5850
06-28 10:48:06.371  5850  5850 D ConnectivityService: filterNetworkStateForUid() uid: 10028, pid: 5850, networkInfo: [type: MOBILE[LTE], state: CONNECTED/CONNECTED, reason: (unspecified), extra: internet, failover: false, available: true, roaming: false]
06-28 10:48:06.372  5850 20293 E BartenderActivityManager: BarTender: pid : 31366 cached=false abnormal=true kill=false stay=false release=true
06-28 10:48:06.373 19940 20031 D SDHMS:Wa: !@SLOWDOWN::call sendControlInfo for cpu slowdown API, , Enable : false, ID : 31366
06-28 10:48:06.375 19940 20031 D SDHMS:ma: writeSysfs:: path = /sys/power/execution_mode_change, value = 0
06-28 10:48:06.376 19940 20031 D SDHMS:ma: writeSysfs:: path = /sys/power/boost_mode_change, value = 1
06-28 10:48:06.377  9399  9399 I o*.d*.j*.StoragePicker: result /
06-28 10:48:06.377  9399  9399 I o*.d*.j*.StoragePicker: test file /test_file.txt
06-28 10:48:06.379  5308  5308 E audit   : type=1400 audit(1593377286.373:28103): avc:  denied  { read } for  pid=9399 comm="org.dkf.jmule" name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app_27:s0:c94,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 SEPF_SM-G973F_10_0015 audit_filtered
06-28 10:48:06.379  5308  5308 E audit   : type=1300 audit(1593377286.373:28103): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=78af8df540 a2=84000 a3=0 items=0 ppid=5323 pid=9399 auid=4294967295 uid=10606 gid=10606 euid=10606 suid=10606 fsuid=10606 egid=10606 sgid=10606 fsgid=10606 tty=(none) ses=4294967295 comm="org.dkf.jmule" exe="/system/bin/app_process64" subj=u:r:untrusted_app_27:s0:c94,c258,c512,c768 key=(null)
06-28 10:48:06.379  5308  5308 E audit   : type=1327 audit(1593377286.373:28103): proctitle="org.dkf.jmule"
06-28 10:48:06.395  9399  9399 W DocumentFile: Failed to createFile: java.io.IOException: Read-only file system
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: Error getting file: /test_file.txt {}
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.support.v4.provider.DocumentFile.getName()' on a null object reference
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at org.dkf.jed2k.android.LollipopFileSystem.getFile(LollipopFileSystem.java:392)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at org.dkf.jed2k.android.LollipopFileSystem.openFD(LollipopFileSystem.java:305)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at org.dkf.jmule.StoragePicker.handle(StoragePicker.java:101)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at org.dkf.jmule.views.preference.StoragePreference.onDocumentTreeActivityResult(StoragePreference.java:166)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at org.dkf.jmule.activities.SettingsActivity.onActivityResult(SettingsActivity.java:390)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.app.Activity.dispatchActivityResult(Activity.java:8294)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5230)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5278)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.os.Looper.loop(Looper.java:237)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at android.app.ActivityThread.main(ActivityThread.java:8016)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at java.lang.reflect.Method.invoke(Native Method)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
06-28 10:48:06.397  9399  9399 E LollipopFileSystem: Unable to obtain or create document for file: /test_file.txt
06-28 10:48:06.397  9399  9399 E o*.d*.j*.StoragePicker: unable to create file /test_file.txt
06-28 10:48:06.397  9399  9399 D ViewRootImpl@b860481[SettingsActivity]: stopped(false) old=true
06-28 10:48:06.397  9399  9399 D ViewRootImpl@b860481[SettingsActivity]: stopped(false) old=false
06-28 10:48:06.397  9399  9399 I SettingsActivity: update storage option /storage/emulated/0/ed2k
06-28 10:48:06.416  5850 20293 V WindowManager: Relayout Window{8b4c178 u0 org.dkf.jmule/org.dkf.jmule.activities.SettingsActivity}: viewVisibility=0 req=1080x2280
06-28 10:48:06.419  5404 11641 I SurfaceFlinger: id=5773 createSurf (1080x2280),1 flag=404, org.dkf.jmule/org.dkf.jmule.activities.SettingsActivity$_9399#0
06-28 10:48:06.421  5850 20293 D WindowManager: makeSurface duration=2 name=org.dkf.jmule/org.dkf.jmule.activities.SettingsActivity$_9399
06-28 10:48:06.422  5850 20293 V WindowManager: Changing focus from null to Window{8b4c178 u0 org.dkf.jmule/org.dkf.jmule.activities.SettingsActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:202 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6276 com.android.server.wm.WindowManagerService.relayoutWindow:2574 com.android.server.wm.Session.relayout:202 android.view.IWindowSession$Stub.onTransact:708 com.android.server.wm.Session.onTransact:142 
06-28 10:48:06.422  5850  5973 D WindowManager: setSystemUiVisibility: displayId=0, vis=0x8018, fullVis=0x2000, dockVis=0x0, win=Window{8b4c178 u0 org.dkf.jmule/org.dkf.jmule.activities.SettingsActivity}
06-28 10:48:06.422  5850 20293 D StatusBarManagerService: notifyRequestedSystemKey recent=false home=false
06-28 10:48:06.423  5850 20293 V WindowManager: Relayout 9399: mAttrs={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x10302fe
06-28 10:48:06.423  5850 20293 V WindowManager:   fl=1810100
06-28 10:48:06.423  5850 20293 V WindowManager:   pfl=10020000
06-28 10:48:06.423  5850 20293 V WindowManager:   vsysui=10 naviIconColor=0}
06-28 10:48:06.423  5850  5975 I WindowManager: Focus moving from null to Window{8b4c178 u0 org.dkf.jmule/org.dkf.jmule.activities.SettingsActivity} displayId=0
````

**Comment by a-pavlov** [comment]
Please try https://github.com/a-pavlov/jed2k/releases/tag/3.0
